_:
  just -l

check-all: _check-desktop _check-embeded
  
_check-desktop:
  cargo check --no-default-features -F desktop && echo "Desktop Check Successful" | lolcat || echo "Desktop Check FAILED" | lolcat

_check-embeded:
  cargo check --no-default-features -F embeded 2> /dev/null && echo "Embeded Check Successful" | lolcat || echo "Embeded Check Failed" | lolcat

