_:
  just -l

_edit-pio-file fname:
  nvim "+setfiletype asm" {{fname}}

edit-i2s-pio:
  @just _edit-pio-file ./src/i2s.pio

_new-window NAME CMD:
  tmux new-w -t pico-synth -n "{{NAME}}"
  tmux send-keys -t pico-synth:"{{NAME}}" "{{CMD}}" ENTER

tmux:
  tmux new -ds pico-synth -n "README"
  tmux send-keys -t pico-synth:README 'nv ./README.md "+set wrap"' ENTER
  @just _new-window "Edit" ""
  @just _new-window "Run" ""
  @just _new-window "Git" "git status"
  @just _new-window "Misc" ""
  tmux a -t pico-synth
